<tr>
    <th>#</th>
    <th>{{ucwords(__('profile::academic.institution'))}}</th>
    <th>{{ucwords(__('profile::academic.study-level'))}}</th>
    <th>{{ucwords(__('profile::academic.start-year'))}}</th>
    <th>{{ucwords(__('profile::academic.end-year'))}}</th>
    <th>{{ucwords(__('profile::academic.result'))}}</th>
    <th>{{ucwords(__('profile::academic.course'))}}</th>
    <th>Action</th>
</tr>
