<tr>
    <th>#</th>
    <th><strong>{{ucwords(__('profile::family-detail.name'))}}</strong></th>
    <th>{{ucwords(__('profile::family-detail.relationship'))}}</th>
    <th>{{ucwords(__('profile::family-detail.ic-number'))}}</th>
    <th>{{ucwords(__('profile::family-detail.mobile-number'))}}</th>
    <th>{{ucwords(__('profile::family-detail.occupation'))}}</th>
    <th>{{ucwords(__('profile::family-detail.income-tax-number'))}}</th>
    <th>Action</th>
</tr>
